"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['downloader.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'youtube-logo.svg'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
